### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by on3iro** [on3iro/4so-web-cookiecutter#1]
- [x] Autoprefixing
- [x] Style-compilation
- [x] check hot reloading
- [x] Uglify CSS in prod
- [x] linting
- [ ] check test runners
- [x] add __mocks__ for tests
